/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystem;

/**
 *
 * @author Nox
 */
public class AddForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddForm.class.getName());
    private MainFrame mainForm;

    /**
     * Creates new form AddForm
     */
    public AddForm(MainFrame mainForm) {
        initComponents();
        this.mainForm = mainForm;
        setLocationRelativeTo(null);
        loadDropdowns();
        setInitialDates();
    }
    
    private void loadDropdowns() {
        // Load Genres
        javax.swing.DefaultComboBoxModel genreModel = new javax.swing.DefaultComboBoxModel();
        for (Genre g : Database.getAllGenres()) {
            genreModel.addElement(g);
        }
        genresComboBox.setModel(genreModel);

        // Load ONLY Available Books for the Borrow tab
        javax.swing.DefaultComboBoxModel bookModel = new javax.swing.DefaultComboBoxModel();
        for (Book b : Database.getAllBooks()) {
            if ("Available".equals(b.getStatus())) {
                bookModel.addElement(b);
            }
        }
        bookComboBox.setModel(bookModel);

        // Load Borrowers
        javax.swing.DefaultComboBoxModel patronModel = new javax.swing.DefaultComboBoxModel();
        for (Borrower b : Database.getAllBorrowers()) {
            patronModel.addElement(b);
        }
        patronComboBox.setModel(patronModel);
    }
    
    private void setInitialDates() {
    java.time.LocalDate today = java.time.LocalDate.now();
    java.time.LocalDate dueDate = today.plusDays(7);

    borrowDateTextField.setText(today.toString()); 
    dueDateTextField.setText(dueDate.toString());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        addBookPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        authorLabel = new javax.swing.JLabel();
        authorTextField = new javax.swing.JTextField();
        genreLabel = new javax.swing.JLabel();
        genresComboBox = new javax.swing.JComboBox<>();
        yearLabel = new javax.swing.JLabel();
        yearTextField = new javax.swing.JTextField();
        addBtn_book = new javax.swing.JButton();
        clearBtn_book = new javax.swing.JButton();
        returnMenuBtn_book = new javax.swing.JButton();
        addBorrowerPanel = new javax.swing.JPanel();
        fnameLabel = new javax.swing.JLabel();
        fnameTextField = new javax.swing.JTextField();
        lnameLabel = new javax.swing.JLabel();
        lnameTextField = new javax.swing.JTextField();
        contactNumLabel = new javax.swing.JLabel();
        contactNumTextField = new javax.swing.JTextField();
        addBtn_borrower = new javax.swing.JButton();
        clearBtn_borrower = new javax.swing.JButton();
        returnMenuBtn_borrower = new javax.swing.JButton();
        issueBookPanel = new javax.swing.JPanel();
        bookLabel = new javax.swing.JLabel();
        bookComboBox = new javax.swing.JComboBox<>();
        patronLabel = new javax.swing.JLabel();
        patronComboBox = new javax.swing.JComboBox<>();
        borrowDateLabel = new javax.swing.JLabel();
        borrowDateTextField = new javax.swing.JTextField();
        dueDateLabel = new javax.swing.JLabel();
        dueDateTextField = new javax.swing.JTextField();
        checkOutBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        returnMenuBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Library Management System");
        setMaximumSize(new java.awt.Dimension(8000, 5500));
        setMinimumSize(new java.awt.Dimension(800, 550));
        setName("AddForm"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 550));

        tabbedPane.setBackground(new java.awt.Color(245, 245, 245));
        tabbedPane.setForeground(new java.awt.Color(13, 13, 13));
        tabbedPane.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        tabbedPane.setMaximumSize(new java.awt.Dimension(8000, 5500));
        tabbedPane.setMinimumSize(new java.awt.Dimension(800, 550));
        tabbedPane.setPreferredSize(new java.awt.Dimension(800, 550));

        addBookPanel.setBackground(new java.awt.Color(245, 245, 245));
        addBookPanel.setForeground(new java.awt.Color(13, 13, 13));
        addBookPanel.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        addBookPanel.setMaximumSize(new java.awt.Dimension(8000, 5500));
        addBookPanel.setMinimumSize(new java.awt.Dimension(800, 550));
        addBookPanel.setName("addBook"); // NOI18N
        addBookPanel.setPreferredSize(new java.awt.Dimension(800, 550));
        addBookPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        titleLabel.setText("Title");
        addBookPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        titleTextField.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        titleTextField.setMinimumSize(new java.awt.Dimension(65, 25));
        titleTextField.addActionListener(this::titleTextFieldActionPerformed);
        addBookPanel.add(titleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 250, 30));

        authorLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        authorLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        authorLabel.setText("Author");
        addBookPanel.add(authorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        authorTextField.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        authorTextField.setMinimumSize(new java.awt.Dimension(65, 25));
        authorTextField.addActionListener(this::authorTextFieldActionPerformed);
        addBookPanel.add(authorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 250, 30));

        genreLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        genreLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        genreLabel.setText("Genre");
        addBookPanel.add(genreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        genresComboBox.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        genresComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addBookPanel.add(genresComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 250, 30));

        yearLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        yearLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yearLabel.setText("Year");
        addBookPanel.add(yearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        yearTextField.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        yearTextField.setMinimumSize(new java.awt.Dimension(65, 25));
        yearTextField.addActionListener(this::yearTextFieldActionPerformed);
        addBookPanel.add(yearTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 250, 30));

        addBtn_book.setBackground(new java.awt.Color(255, 250, 240));
        addBtn_book.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        addBtn_book.setText("ADD");
        addBtn_book.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        addBtn_book.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addBtn_book.setMaximumSize(new java.awt.Dimension(150, 45));
        addBtn_book.setMinimumSize(new java.awt.Dimension(150, 45));
        addBtn_book.setPreferredSize(new java.awt.Dimension(150, 45));
        addBtn_book.setRequestFocusEnabled(false);
        addBtn_book.addActionListener(this::addBtn_bookActionPerformed);
        addBookPanel.add(addBtn_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        clearBtn_book.setBackground(new java.awt.Color(255, 250, 240));
        clearBtn_book.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        clearBtn_book.setText("CLEAR");
        clearBtn_book.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        clearBtn_book.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        clearBtn_book.setMaximumSize(new java.awt.Dimension(150, 45));
        clearBtn_book.setMinimumSize(new java.awt.Dimension(150, 45));
        clearBtn_book.setPreferredSize(new java.awt.Dimension(150, 45));
        clearBtn_book.setRequestFocusEnabled(false);
        clearBtn_book.addActionListener(this::clearBtn_bookActionPerformed);
        addBookPanel.add(clearBtn_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        returnMenuBtn_book.setBackground(new java.awt.Color(255, 250, 240));
        returnMenuBtn_book.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        returnMenuBtn_book.setText("BACK TO MENU");
        returnMenuBtn_book.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        returnMenuBtn_book.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        returnMenuBtn_book.setMaximumSize(new java.awt.Dimension(150, 45));
        returnMenuBtn_book.setMinimumSize(new java.awt.Dimension(150, 45));
        returnMenuBtn_book.setPreferredSize(new java.awt.Dimension(150, 45));
        returnMenuBtn_book.setRequestFocusEnabled(false);
        returnMenuBtn_book.addActionListener(this::returnMenuBtn_bookActionPerformed);
        addBookPanel.add(returnMenuBtn_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, -1, -1));

        tabbedPane.addTab("Add Book", addBookPanel);

        addBorrowerPanel.setBackground(new java.awt.Color(245, 245, 245));
        addBorrowerPanel.setForeground(new java.awt.Color(13, 13, 13));
        addBorrowerPanel.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        addBorrowerPanel.setMaximumSize(new java.awt.Dimension(8000, 5500));
        addBorrowerPanel.setMinimumSize(new java.awt.Dimension(800, 550));
        addBorrowerPanel.setName("addBook"); // NOI18N
        addBorrowerPanel.setPreferredSize(new java.awt.Dimension(800, 550));
        addBorrowerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fnameLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        fnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fnameLabel.setText("First Name");
        addBorrowerPanel.add(fnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        fnameTextField.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        fnameTextField.setMinimumSize(new java.awt.Dimension(65, 25));
        fnameTextField.addActionListener(this::fnameTextFieldActionPerformed);
        addBorrowerPanel.add(fnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 250, 30));

        lnameLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lnameLabel.setText("Last Name");
        addBorrowerPanel.add(lnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        lnameTextField.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        lnameTextField.setMinimumSize(new java.awt.Dimension(65, 25));
        lnameTextField.addActionListener(this::lnameTextFieldActionPerformed);
        addBorrowerPanel.add(lnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 250, 30));

        contactNumLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        contactNumLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        contactNumLabel.setText("Contact Number");
        addBorrowerPanel.add(contactNumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        contactNumTextField.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        contactNumTextField.setMinimumSize(new java.awt.Dimension(65, 25));
        contactNumTextField.addActionListener(this::contactNumTextFieldActionPerformed);
        addBorrowerPanel.add(contactNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 250, 30));

        addBtn_borrower.setBackground(new java.awt.Color(255, 250, 240));
        addBtn_borrower.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        addBtn_borrower.setText("ADD");
        addBtn_borrower.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        addBtn_borrower.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addBtn_borrower.setMaximumSize(new java.awt.Dimension(150, 45));
        addBtn_borrower.setMinimumSize(new java.awt.Dimension(150, 45));
        addBtn_borrower.setPreferredSize(new java.awt.Dimension(150, 45));
        addBtn_borrower.setRequestFocusEnabled(false);
        addBtn_borrower.addActionListener(this::addBtn_borrowerActionPerformed);
        addBorrowerPanel.add(addBtn_borrower, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        clearBtn_borrower.setBackground(new java.awt.Color(255, 250, 240));
        clearBtn_borrower.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        clearBtn_borrower.setText("CLEAR");
        clearBtn_borrower.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        clearBtn_borrower.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        clearBtn_borrower.setMaximumSize(new java.awt.Dimension(150, 45));
        clearBtn_borrower.setMinimumSize(new java.awt.Dimension(150, 45));
        clearBtn_borrower.setPreferredSize(new java.awt.Dimension(150, 45));
        clearBtn_borrower.setRequestFocusEnabled(false);
        clearBtn_borrower.addActionListener(this::clearBtn_borrowerActionPerformed);
        addBorrowerPanel.add(clearBtn_borrower, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        returnMenuBtn_borrower.setBackground(new java.awt.Color(255, 250, 240));
        returnMenuBtn_borrower.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        returnMenuBtn_borrower.setText("BACK TO MENU");
        returnMenuBtn_borrower.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        returnMenuBtn_borrower.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        returnMenuBtn_borrower.setMaximumSize(new java.awt.Dimension(150, 45));
        returnMenuBtn_borrower.setMinimumSize(new java.awt.Dimension(150, 45));
        returnMenuBtn_borrower.setPreferredSize(new java.awt.Dimension(150, 45));
        returnMenuBtn_borrower.setRequestFocusEnabled(false);
        returnMenuBtn_borrower.addActionListener(this::returnMenuBtn_borrowerActionPerformed);
        addBorrowerPanel.add(returnMenuBtn_borrower, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, -1));

        tabbedPane.addTab("Add Borrower", addBorrowerPanel);

        issueBookPanel.setBackground(new java.awt.Color(245, 245, 245));
        issueBookPanel.setForeground(new java.awt.Color(13, 13, 13));
        issueBookPanel.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        issueBookPanel.setMaximumSize(new java.awt.Dimension(8000, 5500));
        issueBookPanel.setMinimumSize(new java.awt.Dimension(800, 550));
        issueBookPanel.setName("addBook"); // NOI18N
        issueBookPanel.setPreferredSize(new java.awt.Dimension(800, 550));
        issueBookPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        bookLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bookLabel.setText("Book");
        issueBookPanel.add(bookLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        bookComboBox.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        bookComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bookComboBox.addActionListener(this::bookComboBoxActionPerformed);
        issueBookPanel.add(bookComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 250, 30));

        patronLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        patronLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        patronLabel.setText("Patron");
        issueBookPanel.add(patronLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        patronComboBox.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        patronComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        issueBookPanel.add(patronComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 250, 30));

        borrowDateLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        borrowDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        borrowDateLabel.setText("Borrow Date (YYYY-MM-DD)");
        issueBookPanel.add(borrowDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        borrowDateTextField.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        borrowDateTextField.setMinimumSize(new java.awt.Dimension(65, 25));
        borrowDateTextField.addActionListener(this::borrowDateTextFieldActionPerformed);
        issueBookPanel.add(borrowDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 250, 30));

        dueDateLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        dueDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dueDateLabel.setText("Due Date (YYYY-MM-DD)");
        issueBookPanel.add(dueDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        dueDateTextField.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        dueDateTextField.setMinimumSize(new java.awt.Dimension(65, 25));
        dueDateTextField.addActionListener(this::dueDateTextFieldActionPerformed);
        issueBookPanel.add(dueDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 250, 30));

        checkOutBtn.setBackground(new java.awt.Color(255, 250, 240));
        checkOutBtn.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        checkOutBtn.setText("CHECK OUT");
        checkOutBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        checkOutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        checkOutBtn.setMaximumSize(new java.awt.Dimension(150, 45));
        checkOutBtn.setMinimumSize(new java.awt.Dimension(150, 45));
        checkOutBtn.setPreferredSize(new java.awt.Dimension(150, 45));
        checkOutBtn.setRequestFocusEnabled(false);
        checkOutBtn.addActionListener(this::checkOutBtnActionPerformed);
        issueBookPanel.add(checkOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        clearBtn.setBackground(new java.awt.Color(255, 250, 240));
        clearBtn.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        clearBtn.setText("CLEAR");
        clearBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        clearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        clearBtn.setMaximumSize(new java.awt.Dimension(150, 45));
        clearBtn.setMinimumSize(new java.awt.Dimension(150, 45));
        clearBtn.setPreferredSize(new java.awt.Dimension(150, 45));
        clearBtn.setRequestFocusEnabled(false);
        clearBtn.addActionListener(this::clearBtnActionPerformed);
        issueBookPanel.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        returnMenuBtn.setBackground(new java.awt.Color(255, 250, 240));
        returnMenuBtn.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        returnMenuBtn.setText("BACK TO MENU");
        returnMenuBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        returnMenuBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        returnMenuBtn.setMaximumSize(new java.awt.Dimension(150, 45));
        returnMenuBtn.setMinimumSize(new java.awt.Dimension(150, 45));
        returnMenuBtn.setPreferredSize(new java.awt.Dimension(150, 45));
        returnMenuBtn.setRequestFocusEnabled(false);
        returnMenuBtn.addActionListener(this::returnMenuBtnActionPerformed);
        issueBookPanel.add(returnMenuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        tabbedPane.addTab("Issue Book (Borrow)", issueBookPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTextFieldActionPerformed

    private void authorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorTextFieldActionPerformed

    private void yearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextFieldActionPerformed

    private void addBtn_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn_bookActionPerformed
        // TODO add your handling code here:
        try {
            String title = titleTextField.getText();
            String author = authorTextField.getText();
            int year = Integer.parseInt(yearTextField.getText());
            
            Genre selectedGenre = (Genre) genresComboBox.getSelectedItem();
            
            Book newBook = new Book(title, author, selectedGenre.getGenreId(), year, "Available");
            Database.addBook(newBook);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Book Added Successfully!");
            clearBtn_bookActionPerformed(evt);
            loadDropdowns();
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Year must be a valid number.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Please check all inputs.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addBtn_bookActionPerformed

    private void returnMenuBtn_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMenuBtn_bookActionPerformed
        // TODO add your handling code here:
        this.dispose();
        mainForm.setVisible(true);
    }//GEN-LAST:event_returnMenuBtn_bookActionPerformed

    private void clearBtn_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn_bookActionPerformed
        // TODO add your handling code here:
        titleTextField.setText("");
        authorTextField.setText("");
        yearTextField.setText("");
        if (genresComboBox.getItemCount() > 0) {
            genresComboBox.setSelectedIndex(0);
        }
    }//GEN-LAST:event_clearBtn_bookActionPerformed

    private void fnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameTextFieldActionPerformed

    private void contactNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumTextFieldActionPerformed

    private void lnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameTextFieldActionPerformed

    private void addBtn_borrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn_borrowerActionPerformed
        // TODO add your handling code here:
        try {
            String fName = fnameTextField.getText();
            String lName = lnameTextField.getText();
            String contact = contactNumTextField.getText();
            
            if (fName.isEmpty() || lName.isEmpty()) {
                throw new IllegalArgumentException("Names cannot be empty.");
            }
            
            Borrower newBorrower = new Borrower(fName, lName, contact);
            Database.addBorrower(newBorrower);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Borrower Added Successfully!");
            clearBtn_borrowerActionPerformed(evt);
            loadDropdowns();
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error adding borrower: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addBtn_borrowerActionPerformed

    private void clearBtn_borrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn_borrowerActionPerformed
        // TODO add your handling code here:
        fnameTextField.setText("");
        lnameTextField.setText("");
        contactNumTextField.setText("");
    }//GEN-LAST:event_clearBtn_borrowerActionPerformed

    private void returnMenuBtn_borrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMenuBtn_borrowerActionPerformed
        // TODO add your handling code here:
        this.dispose();
        mainForm.setVisible(true);
    }//GEN-LAST:event_returnMenuBtn_borrowerActionPerformed

    private void borrowDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrowDateTextFieldActionPerformed

    private void dueDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dueDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dueDateTextFieldActionPerformed

    private void checkOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutBtnActionPerformed
        // TODO add your handling code here:
        try {
            Book selectedBook = (Book) bookComboBox.getSelectedItem();
            Borrower selectedPatron = (Borrower) patronComboBox.getSelectedItem();
            
            if (selectedBook == null || selectedPatron == null) {
                throw new NullPointerException("Please ensure a Book and Patron are selected.");
            }
            
            java.sql.Date borrowDate = java.sql.Date.valueOf(borrowDateTextField.getText());
            java.sql.Date dueDate = java.sql.Date.valueOf(dueDateTextField.getText());
            
            boolean success = Database.borrowBook(selectedBook.getBookId(), selectedPatron.getBorrowerId(), borrowDate, dueDate);
            
            if (success) {
                javax.swing.JOptionPane.showMessageDialog(this, "Book Issued Successfully!");
                clearBtnActionPerformed(evt);
                loadDropdowns();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Database error: Could not process transaction.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (IllegalArgumentException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Date Error: Please use the YYYY-MM-DD format (e.g., 2026-07-24).", "Format Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_checkOutBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        borrowDateTextField.setText("");
        dueDateTextField.setText("");
        if (bookComboBox.getItemCount() > 0) bookComboBox.setSelectedIndex(0);
        if (patronComboBox.getItemCount() > 0) patronComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_clearBtnActionPerformed

    private void returnMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMenuBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        mainForm.setVisible(true);
    }//GEN-LAST:event_returnMenuBtnActionPerformed

    private void bookComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addBookPanel;
    private javax.swing.JPanel addBorrowerPanel;
    private javax.swing.JButton addBtn_book;
    private javax.swing.JButton addBtn_borrower;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JTextField authorTextField;
    private javax.swing.JComboBox<String> bookComboBox;
    private javax.swing.JLabel bookLabel;
    private javax.swing.JLabel borrowDateLabel;
    private javax.swing.JTextField borrowDateTextField;
    private javax.swing.JButton checkOutBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton clearBtn_book;
    private javax.swing.JButton clearBtn_borrower;
    private javax.swing.JLabel contactNumLabel;
    private javax.swing.JTextField contactNumTextField;
    private javax.swing.JLabel dueDateLabel;
    private javax.swing.JTextField dueDateTextField;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JTextField fnameTextField;
    private javax.swing.JLabel genreLabel;
    private javax.swing.JComboBox<String> genresComboBox;
    private javax.swing.JPanel issueBookPanel;
    private javax.swing.JLabel lnameLabel;
    private javax.swing.JTextField lnameTextField;
    private javax.swing.JComboBox<String> patronComboBox;
    private javax.swing.JLabel patronLabel;
    private javax.swing.JButton returnMenuBtn;
    private javax.swing.JButton returnMenuBtn_book;
    private javax.swing.JButton returnMenuBtn_borrower;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTextField;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
