/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystem;

/**
 *
 * @author Nox
 */
public class DeleteForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DeleteForm.class.getName());
    private MainFrame mainForm;

    /**
     * Creates new form DeleteForm
     */
    public DeleteForm(MainFrame mainForm) {
        initComponents();
        this.mainForm = mainForm;
        setLocationRelativeTo(null);
        
        loadBooksTable();
        loadBorrowersTable();
    }
    
    private void loadBooksTable() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new String[]{"ID", "Title", "Author", "Genre", "Year", "Status"}, 0
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        for (Book b : Database.getAllBooks()) {
            model.addRow(new Object[]{
                b.getBookId(), b.getTitle(), b.getAuthor(), b.getGenreName(), b.getPublicationYear(), b.getStatus()
            }); 
        }
        booksTable.setModel(model);
    }

    private void loadBorrowersTable() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new String[]{"ID", "First Name", "Last Name", "Contact Number"}, 0
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        for (Borrower b : Database.getAllBorrowers()) {
            model.addRow(new Object[]{
                b.getBorrowerId(), b.getFirstName(), b.getLastName(), b.getContactNumber()
            }); 
        }
        borrowersTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        deleteBookPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        booksTable = new javax.swing.JTable();
        deleteBtn_book = new javax.swing.JButton();
        returnMenuBtn_book = new javax.swing.JButton();
        deleteBorrowersPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        borrowersTable = new javax.swing.JTable();
        deleteBtn_borrower = new javax.swing.JButton();
        returnMenuBtn_borrower = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Library Management System");
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setName("DeleteForm"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        tabbedPane.setBackground(new java.awt.Color(245, 245, 245));
        tabbedPane.setForeground(new java.awt.Color(13, 13, 13));
        tabbedPane.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        tabbedPane.setMaximumSize(new java.awt.Dimension(1280, 720));
        tabbedPane.setMinimumSize(new java.awt.Dimension(1280, 720));
        tabbedPane.setPreferredSize(new java.awt.Dimension(1280, 720));

        deleteBookPanel.setBackground(new java.awt.Color(245, 245, 245));
        deleteBookPanel.setForeground(new java.awt.Color(13, 13, 13));
        deleteBookPanel.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        deleteBookPanel.setMaximumSize(new java.awt.Dimension(1280, 720));
        deleteBookPanel.setMinimumSize(new java.awt.Dimension(1280, 720));
        deleteBookPanel.setName("addBook"); // NOI18N
        deleteBookPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        deleteBookPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        booksTable.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        booksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(booksTable);

        deleteBookPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1060, 660));

        deleteBtn_book.setBackground(new java.awt.Color(255, 250, 240));
        deleteBtn_book.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        deleteBtn_book.setText("DELETE");
        deleteBtn_book.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        deleteBtn_book.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        deleteBtn_book.setMaximumSize(new java.awt.Dimension(150, 45));
        deleteBtn_book.setMinimumSize(new java.awt.Dimension(150, 45));
        deleteBtn_book.setPreferredSize(new java.awt.Dimension(150, 45));
        deleteBtn_book.setRequestFocusEnabled(false);
        deleteBtn_book.addActionListener(this::deleteBtn_bookActionPerformed);
        deleteBookPanel.add(deleteBtn_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 60, -1, -1));

        returnMenuBtn_book.setBackground(new java.awt.Color(255, 250, 240));
        returnMenuBtn_book.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        returnMenuBtn_book.setText("BACK TO MENU");
        returnMenuBtn_book.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        returnMenuBtn_book.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        returnMenuBtn_book.setMaximumSize(new java.awt.Dimension(150, 45));
        returnMenuBtn_book.setMinimumSize(new java.awt.Dimension(150, 45));
        returnMenuBtn_book.setPreferredSize(new java.awt.Dimension(150, 45));
        returnMenuBtn_book.setRequestFocusEnabled(false);
        returnMenuBtn_book.addActionListener(this::returnMenuBtn_bookActionPerformed);
        deleteBookPanel.add(returnMenuBtn_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 130, -1, -1));

        tabbedPane.addTab("Delete Books", deleteBookPanel);

        deleteBorrowersPanel.setBackground(new java.awt.Color(245, 245, 245));
        deleteBorrowersPanel.setForeground(new java.awt.Color(13, 13, 13));
        deleteBorrowersPanel.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        deleteBorrowersPanel.setMaximumSize(new java.awt.Dimension(1280, 720));
        deleteBorrowersPanel.setMinimumSize(new java.awt.Dimension(1280, 720));
        deleteBorrowersPanel.setName("addBook"); // NOI18N
        deleteBorrowersPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        deleteBorrowersPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        borrowersTable.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        borrowersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(borrowersTable);

        deleteBorrowersPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1060, 660));

        deleteBtn_borrower.setBackground(new java.awt.Color(255, 250, 240));
        deleteBtn_borrower.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        deleteBtn_borrower.setText("DELETE");
        deleteBtn_borrower.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        deleteBtn_borrower.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        deleteBtn_borrower.setMaximumSize(new java.awt.Dimension(150, 45));
        deleteBtn_borrower.setMinimumSize(new java.awt.Dimension(150, 45));
        deleteBtn_borrower.setPreferredSize(new java.awt.Dimension(150, 45));
        deleteBtn_borrower.setRequestFocusEnabled(false);
        deleteBtn_borrower.addActionListener(this::deleteBtn_borrowerActionPerformed);
        deleteBorrowersPanel.add(deleteBtn_borrower, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 60, -1, -1));

        returnMenuBtn_borrower.setBackground(new java.awt.Color(255, 250, 240));
        returnMenuBtn_borrower.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        returnMenuBtn_borrower.setText("BACK TO MENU");
        returnMenuBtn_borrower.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        returnMenuBtn_borrower.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        returnMenuBtn_borrower.setMaximumSize(new java.awt.Dimension(150, 45));
        returnMenuBtn_borrower.setMinimumSize(new java.awt.Dimension(150, 45));
        returnMenuBtn_borrower.setPreferredSize(new java.awt.Dimension(150, 45));
        returnMenuBtn_borrower.setRequestFocusEnabled(false);
        returnMenuBtn_borrower.addActionListener(this::returnMenuBtn_borrowerActionPerformed);
        deleteBorrowersPanel.add(returnMenuBtn_borrower, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 130, -1, -1));

        tabbedPane.addTab("Delete Patrons", deleteBorrowersPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnMenuBtn_borrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMenuBtn_borrowerActionPerformed
        // TODO add your handling code here:
        this.dispose();
        mainForm.setVisible(true);
    }//GEN-LAST:event_returnMenuBtn_borrowerActionPerformed

    private void deleteBtn_borrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn_borrowerActionPerformed
        // TODO add your handling code here:
        int selectedRow = borrowersTable.getSelectedRow();
        if (selectedRow != -1) {
            int borrowerId = (int) borrowersTable.getValueAt(selectedRow, 0);
            String fName = borrowersTable.getValueAt(selectedRow, 1).toString();
            String lName = borrowersTable.getValueAt(selectedRow, 2).toString();
            
            int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this, 
                "Are you sure you want to permanently delete patron '" + fName + " " + lName + "'?", 
                "Confirm Deletion", 
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            
            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                try {
                    Database.deleteBorrower(borrowerId);
                    javax.swing.JOptionPane.showMessageDialog(this, "Patron deleted successfully!");
                    loadBorrowersTable(); 
                } catch (Exception e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Cannot delete patron. Please ensure they have returned all borrowed books first.", "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a patron from the table first.");
        }
    }//GEN-LAST:event_deleteBtn_borrowerActionPerformed

    private void deleteBtn_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn_bookActionPerformed
        // TODO add your handling code here:
        int selectedRow = booksTable.getSelectedRow();
        if (selectedRow != -1) {
            int bookId = (int) booksTable.getValueAt(selectedRow, 0);
            String title = booksTable.getValueAt(selectedRow, 1).toString();
            
            // Pop up a warning box
            int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this, 
                "Are you sure you want to permanently delete '" + title + "'?", 
                "Confirm Deletion", 
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            
            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                
                boolean success = Database.deleteBook(bookId);
                
                if (success) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Book and its borrow history deleted successfully!");
                    loadBooksTable();
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Database error: Could not delete book.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a book from the table first.");
        }
    }//GEN-LAST:event_deleteBtn_bookActionPerformed

    private void returnMenuBtn_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMenuBtn_bookActionPerformed
        // TODO add your handling code here:
        this.dispose();
        mainForm.setVisible(true);
    }//GEN-LAST:event_returnMenuBtn_bookActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable booksTable;
    private javax.swing.JTable borrowersTable;
    private javax.swing.JPanel deleteBookPanel;
    private javax.swing.JPanel deleteBorrowersPanel;
    private javax.swing.JButton deleteBtn_book;
    private javax.swing.JButton deleteBtn_borrower;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton returnMenuBtn_book;
    private javax.swing.JButton returnMenuBtn_borrower;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
