/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystem;

/**
 *
 * @author Nox
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(800, 550));
        setMinimumSize(new java.awt.Dimension(800, 550));
        setName("MainFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(800, 550));

        panel.setBackground(new java.awt.Color(245, 245, 245));
        panel.setForeground(new java.awt.Color(13, 13, 13));
        panel.setToolTipText("");
        panel.setFocusable(false);
        panel.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        panel.setMaximumSize(new java.awt.Dimension(800, 550));
        panel.setMinimumSize(new java.awt.Dimension(800, 550));
        panel.setPreferredSize(new java.awt.Dimension(800, 550));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        heading.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        heading.setForeground(new java.awt.Color(51, 61, 41));
        heading.setText("Library Management System");
        panel.add(heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        logo.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/logo.png"))); // NOI18N
        panel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, 160));

        addBtn.setBackground(new java.awt.Color(255, 250, 240));
        addBtn.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        addBtn.setText("ADD");
        addBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addBtn.setMaximumSize(new java.awt.Dimension(150, 45));
        addBtn.setMinimumSize(new java.awt.Dimension(150, 45));
        addBtn.setPreferredSize(new java.awt.Dimension(150, 45));
        addBtn.setRequestFocusEnabled(false);
        addBtn.addActionListener(this::addBtnActionPerformed);
        panel.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        viewBtn.setBackground(new java.awt.Color(255, 250, 240));
        viewBtn.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        viewBtn.setText("VIEW");
        viewBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        viewBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        viewBtn.setMaximumSize(new java.awt.Dimension(150, 45));
        viewBtn.setMinimumSize(new java.awt.Dimension(150, 45));
        viewBtn.setPreferredSize(new java.awt.Dimension(150, 45));
        viewBtn.addActionListener(this::viewBtnActionPerformed);
        panel.add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        deleteBtn.setBackground(new java.awt.Color(255, 250, 240));
        deleteBtn.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        deleteBtn.setText("DELETE");
        deleteBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        deleteBtn.setMaximumSize(new java.awt.Dimension(150, 45));
        deleteBtn.setMinimumSize(new java.awt.Dimension(150, 45));
        deleteBtn.setPreferredSize(new java.awt.Dimension(150, 45));
        deleteBtn.addActionListener(this::deleteBtnActionPerformed);
        panel.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        exitBtn.setBackground(new java.awt.Color(255, 250, 240));
        exitBtn.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        exitBtn.setText("EXIT");
        exitBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitBtn.setMaximumSize(new java.awt.Dimension(150, 45));
        exitBtn.setMinimumSize(new java.awt.Dimension(150, 45));
        exitBtn.setPreferredSize(new java.awt.Dimension(150, 45));
        exitBtn.addActionListener(this::exitBtnActionPerformed);
        panel.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        AddForm addForm = new AddForm(this);
        addForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        ViewForm viewForm = new ViewForm(this);
        viewForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        DeleteForm deleteForm = new DeleteForm(this);
        deleteForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panel;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
