/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystem;

/**
 *
 * @author Nox
 */
public class ViewForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewForm.class.getName());
    private MainFrame mainForm;
    private int selectedBookId = -1;
    private int selectedBorrowerId = -1;

    /**
     * Creates new form View_Form
     */
    public ViewForm(MainFrame mainForm) {
        initComponents();
        this.mainForm = mainForm;
        setLocationRelativeTo(null);
        
        loadDropdowns();
        loadBooksTable();
        loadBorrowersTable();
        loadBorrowRecordsTable();
    }
    
    private void loadDropdowns() {
        javax.swing.DefaultComboBoxModel genreModel = new javax.swing.DefaultComboBoxModel();
        for (Genre g : Database.getAllGenres()) { 
            genreModel.addElement(g);
        }
        genresComboBox.setModel(genreModel);
    }
    
    private void loadBooksTable() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new String[]{"ID", "Title", "Author", "Genre", "Year", "Status"}, 0
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        for (Book b : Database.getAllBooks()) {
            model.addRow(new Object[]{
                b.getBookId(), b.getTitle(), b.getAuthor(), b.getGenreName(), b.getPublicationYear(), b.getStatus()
            }); 
        }
        bookTable.setModel(model); 
    }
    
    private void loadBorrowersTable() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new String[]{"ID", "First Name", "Last Name", "Contact Number"}, 0
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        for (Borrower b : Database.getAllBorrowers()) {
            model.addRow(new Object[]{
                b.getBorrowerId(), b.getFirstName(), b.getLastName(), b.getContactNumber()
            }); 
        }
        bookTable1.setModel(model); 
    }
    
    private void loadBorrowRecordsTable() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new String[]{"Record ID", "Book ID", "Book Title", "Patron Name", "Borrow Date", "Due Date", "Return Date"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        for (BorrowRecord br : Database.getAllBorrowRecords()) {
            String returnStatus = (br.getReturnDate() != null) ? br.getReturnDate().toString() : "Not Returned";
            
            model.addRow(new Object[]{
                br.getBorrowId(), br.getBookId(), br.getBookTitle(), br.getPatronName(),
                br.getBorrowDate(), br.getDueDate(), returnStatus
            }); 
        }
        borrowRecordsTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        viewBookPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        titleLabel = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        authorLabel = new javax.swing.JLabel();
        authorTextField = new javax.swing.JTextField();
        genreLabel = new javax.swing.JLabel();
        genresComboBox = new javax.swing.JComboBox<>();
        yearLabel = new javax.swing.JLabel();
        yearTextField = new javax.swing.JTextField();
        updateBtn_book = new javax.swing.JButton();
        editBtn_book = new javax.swing.JButton();
        clearBtn_book = new javax.swing.JButton();
        returnMenuBtn_book = new javax.swing.JButton();
        viewBorrowersPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookTable1 = new javax.swing.JTable();
        fnameLabel = new javax.swing.JLabel();
        fnameTextField = new javax.swing.JTextField();
        lnameLabel = new javax.swing.JLabel();
        lnameTextField = new javax.swing.JTextField();
        contactNumLabel = new javax.swing.JLabel();
        contactNumTextField = new javax.swing.JTextField();
        updateBtn_borrower = new javax.swing.JButton();
        editBtn_borrower = new javax.swing.JButton();
        clearBtn_borrower = new javax.swing.JButton();
        returnMenuBtn_borrower = new javax.swing.JButton();
        bookCardPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        borrowRecordsTable = new javax.swing.JTable();
        returnBookBtn = new javax.swing.JButton();
        returnMenuBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Library Management System");
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setName("ViewForm"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        tabbedPane.setBackground(new java.awt.Color(245, 245, 245));
        tabbedPane.setForeground(new java.awt.Color(13, 13, 13));
        tabbedPane.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        tabbedPane.setMaximumSize(new java.awt.Dimension(1280, 720));
        tabbedPane.setMinimumSize(new java.awt.Dimension(1280, 720));
        tabbedPane.setPreferredSize(new java.awt.Dimension(1280, 720));

        viewBookPanel.setBackground(new java.awt.Color(245, 245, 245));
        viewBookPanel.setForeground(new java.awt.Color(13, 13, 13));
        viewBookPanel.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        viewBookPanel.setMaximumSize(new java.awt.Dimension(1280, 720));
        viewBookPanel.setMinimumSize(new java.awt.Dimension(1280, 720));
        viewBookPanel.setName("addBook"); // NOI18N
        viewBookPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        viewBookPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookTable.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(bookTable);

        viewBookPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1280, 410));

        titleLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        titleLabel.setText("Title");
        viewBookPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        titleTextField.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        titleTextField.setMinimumSize(new java.awt.Dimension(65, 25));
        titleTextField.addActionListener(this::titleTextFieldActionPerformed);
        viewBookPanel.add(titleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 250, 30));

        authorLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        authorLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        authorLabel.setText("Author");
        viewBookPanel.add(authorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, -1, -1));

        authorTextField.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        authorTextField.setMinimumSize(new java.awt.Dimension(65, 25));
        authorTextField.addActionListener(this::authorTextFieldActionPerformed);
        viewBookPanel.add(authorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 250, 30));

        genreLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        genreLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        genreLabel.setText("Genre");
        viewBookPanel.add(genreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, -1));

        genresComboBox.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        genresComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        viewBookPanel.add(genresComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 250, 30));

        yearLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        yearLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yearLabel.setText("Year");
        viewBookPanel.add(yearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, -1, -1));

        yearTextField.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        yearTextField.setMinimumSize(new java.awt.Dimension(65, 25));
        yearTextField.addActionListener(this::yearTextFieldActionPerformed);
        viewBookPanel.add(yearTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, 250, 30));

        updateBtn_book.setBackground(new java.awt.Color(255, 250, 240));
        updateBtn_book.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        updateBtn_book.setText("UPDATE");
        updateBtn_book.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        updateBtn_book.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        updateBtn_book.setMaximumSize(new java.awt.Dimension(150, 45));
        updateBtn_book.setMinimumSize(new java.awt.Dimension(150, 45));
        updateBtn_book.setPreferredSize(new java.awt.Dimension(150, 45));
        updateBtn_book.setRequestFocusEnabled(false);
        updateBtn_book.addActionListener(this::updateBtn_bookActionPerformed);
        viewBookPanel.add(updateBtn_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 460, -1, -1));

        editBtn_book.setBackground(new java.awt.Color(255, 250, 240));
        editBtn_book.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        editBtn_book.setText("EDIT");
        editBtn_book.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        editBtn_book.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        editBtn_book.setMaximumSize(new java.awt.Dimension(150, 45));
        editBtn_book.setMinimumSize(new java.awt.Dimension(150, 45));
        editBtn_book.setPreferredSize(new java.awt.Dimension(150, 45));
        editBtn_book.setRequestFocusEnabled(false);
        editBtn_book.addActionListener(this::editBtn_bookActionPerformed);
        viewBookPanel.add(editBtn_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 460, -1, -1));

        clearBtn_book.setBackground(new java.awt.Color(255, 250, 240));
        clearBtn_book.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        clearBtn_book.setText("CLEAR");
        clearBtn_book.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        clearBtn_book.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        clearBtn_book.setMaximumSize(new java.awt.Dimension(150, 45));
        clearBtn_book.setMinimumSize(new java.awt.Dimension(150, 45));
        clearBtn_book.setPreferredSize(new java.awt.Dimension(150, 45));
        clearBtn_book.setRequestFocusEnabled(false);
        clearBtn_book.addActionListener(this::clearBtn_bookActionPerformed);
        viewBookPanel.add(clearBtn_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 530, -1, -1));

        returnMenuBtn_book.setBackground(new java.awt.Color(255, 250, 240));
        returnMenuBtn_book.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        returnMenuBtn_book.setText("BACK TO MENU");
        returnMenuBtn_book.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        returnMenuBtn_book.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        returnMenuBtn_book.setMaximumSize(new java.awt.Dimension(150, 45));
        returnMenuBtn_book.setMinimumSize(new java.awt.Dimension(150, 45));
        returnMenuBtn_book.setPreferredSize(new java.awt.Dimension(150, 45));
        returnMenuBtn_book.setRequestFocusEnabled(false);
        returnMenuBtn_book.addActionListener(this::returnMenuBtn_bookActionPerformed);
        viewBookPanel.add(returnMenuBtn_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 530, -1, -1));

        tabbedPane.addTab("View Books", viewBookPanel);

        viewBorrowersPanel.setBackground(new java.awt.Color(245, 245, 245));
        viewBorrowersPanel.setForeground(new java.awt.Color(13, 13, 13));
        viewBorrowersPanel.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        viewBorrowersPanel.setMaximumSize(new java.awt.Dimension(1280, 720));
        viewBorrowersPanel.setMinimumSize(new java.awt.Dimension(1280, 720));
        viewBorrowersPanel.setName("addBook"); // NOI18N
        viewBorrowersPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        viewBorrowersPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookTable1.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        bookTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(bookTable1);

        viewBorrowersPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1280, 410));

        fnameLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        fnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fnameLabel.setText("First Name");
        viewBorrowersPanel.add(fnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        fnameTextField.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        fnameTextField.setMinimumSize(new java.awt.Dimension(65, 25));
        fnameTextField.addActionListener(this::fnameTextFieldActionPerformed);
        viewBorrowersPanel.add(fnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 250, 30));

        lnameLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lnameLabel.setText("Last Name");
        viewBorrowersPanel.add(lnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, -1, -1));

        lnameTextField.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        lnameTextField.setMinimumSize(new java.awt.Dimension(65, 25));
        lnameTextField.addActionListener(this::lnameTextFieldActionPerformed);
        viewBorrowersPanel.add(lnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 250, 30));

        contactNumLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        contactNumLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        contactNumLabel.setText("Contact Number");
        viewBorrowersPanel.add(contactNumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, -1));

        contactNumTextField.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        contactNumTextField.setMinimumSize(new java.awt.Dimension(65, 25));
        contactNumTextField.addActionListener(this::contactNumTextFieldActionPerformed);
        viewBorrowersPanel.add(contactNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 250, 30));

        updateBtn_borrower.setBackground(new java.awt.Color(255, 250, 240));
        updateBtn_borrower.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        updateBtn_borrower.setText("UPDATE");
        updateBtn_borrower.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        updateBtn_borrower.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        updateBtn_borrower.setMaximumSize(new java.awt.Dimension(150, 45));
        updateBtn_borrower.setMinimumSize(new java.awt.Dimension(150, 45));
        updateBtn_borrower.setPreferredSize(new java.awt.Dimension(150, 45));
        updateBtn_borrower.setRequestFocusEnabled(false);
        updateBtn_borrower.addActionListener(this::updateBtn_borrowerActionPerformed);
        viewBorrowersPanel.add(updateBtn_borrower, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 460, -1, -1));

        editBtn_borrower.setBackground(new java.awt.Color(255, 250, 240));
        editBtn_borrower.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        editBtn_borrower.setText("EDIT");
        editBtn_borrower.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        editBtn_borrower.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        editBtn_borrower.setMaximumSize(new java.awt.Dimension(150, 45));
        editBtn_borrower.setMinimumSize(new java.awt.Dimension(150, 45));
        editBtn_borrower.setPreferredSize(new java.awt.Dimension(150, 45));
        editBtn_borrower.setRequestFocusEnabled(false);
        editBtn_borrower.addActionListener(this::editBtn_borrowerActionPerformed);
        viewBorrowersPanel.add(editBtn_borrower, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 460, -1, -1));

        clearBtn_borrower.setBackground(new java.awt.Color(255, 250, 240));
        clearBtn_borrower.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        clearBtn_borrower.setText("CLEAR");
        clearBtn_borrower.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        clearBtn_borrower.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        clearBtn_borrower.setMaximumSize(new java.awt.Dimension(150, 45));
        clearBtn_borrower.setMinimumSize(new java.awt.Dimension(150, 45));
        clearBtn_borrower.setPreferredSize(new java.awt.Dimension(150, 45));
        clearBtn_borrower.setRequestFocusEnabled(false);
        clearBtn_borrower.addActionListener(this::clearBtn_borrowerActionPerformed);
        viewBorrowersPanel.add(clearBtn_borrower, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 530, -1, -1));

        returnMenuBtn_borrower.setBackground(new java.awt.Color(255, 250, 240));
        returnMenuBtn_borrower.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        returnMenuBtn_borrower.setText("BACK TO MENU");
        returnMenuBtn_borrower.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        returnMenuBtn_borrower.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        returnMenuBtn_borrower.setMaximumSize(new java.awt.Dimension(150, 45));
        returnMenuBtn_borrower.setMinimumSize(new java.awt.Dimension(150, 45));
        returnMenuBtn_borrower.setPreferredSize(new java.awt.Dimension(150, 45));
        returnMenuBtn_borrower.setRequestFocusEnabled(false);
        returnMenuBtn_borrower.addActionListener(this::returnMenuBtn_borrowerActionPerformed);
        viewBorrowersPanel.add(returnMenuBtn_borrower, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 530, -1, -1));

        tabbedPane.addTab("View Patrons", viewBorrowersPanel);

        bookCardPanel.setBackground(new java.awt.Color(245, 245, 245));
        bookCardPanel.setForeground(new java.awt.Color(13, 13, 13));
        bookCardPanel.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        bookCardPanel.setMaximumSize(new java.awt.Dimension(1280, 720));
        bookCardPanel.setMinimumSize(new java.awt.Dimension(1280, 720));
        bookCardPanel.setName("addBook"); // NOI18N
        bookCardPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        bookCardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        borrowRecordsTable.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        borrowRecordsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        borrowRecordsTable.setMaximumSize(new java.awt.Dimension(300, 80));
        borrowRecordsTable.setMinimumSize(new java.awt.Dimension(300, 80));
        jScrollPane3.setViewportView(borrowRecordsTable);

        bookCardPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1280, 530));

        returnBookBtn.setBackground(new java.awt.Color(255, 250, 240));
        returnBookBtn.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        returnBookBtn.setText("RETURN BOOK");
        returnBookBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        returnBookBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        returnBookBtn.setMaximumSize(new java.awt.Dimension(150, 45));
        returnBookBtn.setMinimumSize(new java.awt.Dimension(150, 45));
        returnBookBtn.setPreferredSize(new java.awt.Dimension(150, 45));
        returnBookBtn.setRequestFocusEnabled(false);
        returnBookBtn.addActionListener(this::returnBookBtnActionPerformed);
        bookCardPanel.add(returnBookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, -1, -1));

        returnMenuBtn.setBackground(new java.awt.Color(255, 250, 240));
        returnMenuBtn.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        returnMenuBtn.setText("BACK TO MENU");
        returnMenuBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(166, 138, 100), 3, true));
        returnMenuBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        returnMenuBtn.setMaximumSize(new java.awt.Dimension(150, 45));
        returnMenuBtn.setMinimumSize(new java.awt.Dimension(150, 45));
        returnMenuBtn.setPreferredSize(new java.awt.Dimension(150, 45));
        returnMenuBtn.setRequestFocusEnabled(false);
        returnMenuBtn.addActionListener(this::returnMenuBtnActionPerformed);
        bookCardPanel.add(returnMenuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, -1, -1));

        tabbedPane.addTab("Book Card Log", bookCardPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editBtn_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtn_bookActionPerformed
        // TODO add your handling code here:
        int selectedRow = bookTable.getSelectedRow();
        if (selectedRow != -1) {
            selectedBookId = (int) bookTable.getValueAt(selectedRow, 0);
            titleTextField.setText(bookTable.getValueAt(selectedRow, 1).toString());
            authorTextField.setText(bookTable.getValueAt(selectedRow, 2).toString());
            yearTextField.setText(bookTable.getValueAt(selectedRow, 4).toString());
            
            String genreName = bookTable.getValueAt(selectedRow, 3).toString();
            
            javax.swing.DefaultComboBoxModel rawModel = (javax.swing.DefaultComboBoxModel) genresComboBox.getModel();
            
            for (int i = 0; i < rawModel.getSize(); i++) {
                Genre g = (Genre) rawModel.getElementAt(i); 
                
                if (g.getGenreName().equals(genreName)) {
                    genresComboBox.setSelectedIndex(i);
                    break;
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a book from the table first.");
        }
    }//GEN-LAST:event_editBtn_bookActionPerformed

    private void clearBtn_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn_bookActionPerformed
        // TODO add your handling code here:
        titleTextField.setText("");
        authorTextField.setText("");
        yearTextField.setText("");
        if (genresComboBox.getItemCount() > 0) genresComboBox.setSelectedIndex(0);
        selectedBookId = -1;
        bookTable.clearSelection();
    }//GEN-LAST:event_clearBtn_bookActionPerformed

    private void returnMenuBtn_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMenuBtn_bookActionPerformed
        // TODO add your handling code here:
        this.dispose();
        mainForm.setVisible(true);
    }//GEN-LAST:event_returnMenuBtn_bookActionPerformed

    private void yearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextFieldActionPerformed

    private void authorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorTextFieldActionPerformed

    private void titleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTextFieldActionPerformed

    private void updateBtn_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtn_bookActionPerformed
        // TODO add your handling code here:
        if (selectedBookId == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please edit a book first.");
            return;
        }
        try {
            String title = titleTextField.getText();
            String author = authorTextField.getText();
            int year = Integer.parseInt(yearTextField.getText());
            Genre selectedGenre = (Genre) genresComboBox.getSelectedItem();
            
            int selectedRow = bookTable.getSelectedRow();
            String status = (selectedRow != -1) ? bookTable.getValueAt(selectedRow, 5).toString() : "Available";
            
            Book updatedBook = new Book(selectedBookId, title, author, selectedGenre.getGenreId(), selectedGenre.getGenreName(), year, status);
            Database.updateBook(updatedBook);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Book Updated Successfully!");
            clearBtn_bookActionPerformed(evt);
            loadBooksTable();
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Year must be a valid number.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateBtn_bookActionPerformed

    private void editBtn_borrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtn_borrowerActionPerformed
        // TODO add your handling code here:
        int selectedRow = bookTable1.getSelectedRow();
        if (selectedRow != -1) {
            selectedBorrowerId = (int) bookTable1.getValueAt(selectedRow, 0);
            fnameTextField.setText(bookTable1.getValueAt(selectedRow, 1).toString());
            lnameTextField.setText(bookTable1.getValueAt(selectedRow, 2).toString());
            contactNumTextField.setText(bookTable1.getValueAt(selectedRow, 3).toString());
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a patron from the table first.");
        }
    }//GEN-LAST:event_editBtn_borrowerActionPerformed

    private void clearBtn_borrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn_borrowerActionPerformed
        // TODO add your handling code here:
        fnameTextField.setText("");
        lnameTextField.setText("");
        contactNumTextField.setText("");
        selectedBorrowerId = -1;
        bookTable1.clearSelection();
    }//GEN-LAST:event_clearBtn_borrowerActionPerformed

    private void returnMenuBtn_borrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMenuBtn_borrowerActionPerformed
        // TODO add your handling code here:
        this.dispose();
        mainForm.setVisible(true);
    }//GEN-LAST:event_returnMenuBtn_borrowerActionPerformed

    private void updateBtn_borrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtn_borrowerActionPerformed
        // TODO add your handling code here:
        if (selectedBorrowerId == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please edit a patron first.");
            return;
        }
        try {
            String fName = fnameTextField.getText();
            String lName = lnameTextField.getText();
            String contact = contactNumTextField.getText();
            
            Borrower updatedBorrower = new Borrower(selectedBorrowerId, fName, lName, contact);
            Database.updateBorrower(updatedBorrower);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Patron Updated Successfully!");
            clearBtn_borrowerActionPerformed(evt);
            loadBorrowersTable();
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error updating patron.");
        }
    }//GEN-LAST:event_updateBtn_borrowerActionPerformed

    private void returnMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMenuBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        mainForm.setVisible(true);
    }//GEN-LAST:event_returnMenuBtnActionPerformed

    private void fnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameTextFieldActionPerformed

    private void lnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameTextFieldActionPerformed

    private void contactNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumTextFieldActionPerformed

    private void returnBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = borrowRecordsTable.getSelectedRow();
        
        if (selectedRow != -1) {
            String returnStatus = borrowRecordsTable.getValueAt(selectedRow, 6).toString();
            
            if (!returnStatus.equals("Not Returned")) {
                javax.swing.JOptionPane.showMessageDialog(this, "This book has already been returned!");
                return;
            }
            
            int borrowId = (int) borrowRecordsTable.getValueAt(selectedRow, 0);
            int bookId = (int) borrowRecordsTable.getValueAt(selectedRow, 1);
            
            int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this, 
                "Process return for this book?", 
                "Confirm Return", 
                javax.swing.JOptionPane.YES_NO_OPTION
            );
            
            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                java.sql.Date today = java.sql.Date.valueOf(java.time.LocalDate.now());
                
                boolean success = Database.returnBook(borrowId, bookId, today);
                
                if (success) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Book returned successfully!");
                    loadBorrowRecordsTable();
                    loadBooksTable(); 
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Database error: Could not process return.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a record from the log first.");
        }
    }//GEN-LAST:event_returnBookBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLabel;
    private javax.swing.JTextField authorTextField;
    private javax.swing.JPanel bookCardPanel;
    private javax.swing.JTable bookTable;
    private javax.swing.JTable bookTable1;
    private javax.swing.JTable borrowRecordsTable;
    private javax.swing.JButton clearBtn_book;
    private javax.swing.JButton clearBtn_borrower;
    private javax.swing.JLabel contactNumLabel;
    private javax.swing.JTextField contactNumTextField;
    private javax.swing.JButton editBtn_book;
    private javax.swing.JButton editBtn_borrower;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JTextField fnameTextField;
    private javax.swing.JLabel genreLabel;
    private javax.swing.JComboBox<String> genresComboBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lnameLabel;
    private javax.swing.JTextField lnameTextField;
    private javax.swing.JButton returnBookBtn;
    private javax.swing.JButton returnMenuBtn;
    private javax.swing.JButton returnMenuBtn_book;
    private javax.swing.JButton returnMenuBtn_borrower;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTextField;
    private javax.swing.JButton updateBtn_book;
    private javax.swing.JButton updateBtn_borrower;
    private javax.swing.JPanel viewBookPanel;
    private javax.swing.JPanel viewBorrowersPanel;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
